function attachGameRoutes(app, { db, auth }){
  const { getAuthTgid } = auth;
  const gameRooms = new Map();
  let nextRoomId = 1;
  const userActiveRoom = new Map();
  function serializeRoom(room){ return { id: room.id, game: room.game, bet: room.bet, status: room.status, creator: room.creator, opponent: room.opponent, createdAt: room.createdAt, state: room.state, deadlineAt: room.deadlineAt || null }; }
  function clearRoomTimer(room){ try { if (room._timer) { clearTimeout(room._timer); room._timer = null; } } catch(e){} }
  async function finishRoomWithWinner(room, winnerTgid, reason){ try{ if (room.status === 'finished') return; clearRoomTimer(room); room.status = 'finished'; if (winnerTgid) { await db.creditScube(Number(winnerTgid), room.bet * 2); if (room.game === 'rps') { room.state = room.state || {}; room.state.result = Object.assign({}, room.state.result || {}, { type:'win', winner: String(winnerTgid), reason }); } else if (room.game === 'ttt') { room.state = room.state || {}; room.state.winner = String(winnerTgid); room.state.reason = reason; } } else { await db.creditScube(room.creator, room.bet); if (room.opponent) await db.creditScube(room.opponent, room.bet); if (room.game === 'rps') { room.state = room.state || {}; room.state.result = Object.assign({}, room.state.result || {}, { type:'draw', reason }); } else if (room.game === 'ttt') { room.state = room.state || {}; room.state.winner = null; room.state.reason = reason || 'draw'; } } } finally { userActiveRoom.delete(String(room.creator)); if (room.opponent) userActiveRoom.delete(String(room.opponent)); } }
  function startRpsTimer(room){ clearRoomTimer(room); room.deadlineAt = Date.now() + 30000; room._timer = setTimeout(async ()=>{ try{ if (room.status !== 'active') return; const moves = room.state && room.state.moves || {}; const a = moves[String(room.creator)]; const b = moves[String(room.opponent)]; if (a && b) return; if (a && !b) { await finishRoomWithWinner(room, room.creator, 'timeout'); } else if (!a && b) { await finishRoomWithWinner(room, room.opponent, 'timeout'); } else { await finishRoomWithWinner(room, null, 'timeout'); } } catch(e){} }, 30000); }
  function startTttTimer(room){ clearRoomTimer(room); if (!room.state || !room.state.turn) return; const turnTgid = String(room.state.turn); room.deadlineAt = Date.now() + 30000; room._timer = setTimeout(async ()=>{ try{ if (room.status !== 'active') return; const loser = turnTgid; const winner = String(loser) === String(room.creator) ? room.opponent : room.creator; if (!winner) return; await finishRoomWithWinner(room, winner, 'timeout'); } catch(e){} }, 30000); }
  function createRoom(tgid, game, bet){ const id = String(nextRoomId++); const room = { id, game, bet, creator: tgid, opponent: null, status: 'waiting', createdAt: Date.now(), state: game === 'rps' ? { moves: {}, notice: 'Сделайте ход за 30 секунд, иначе поражение.' } : { board: Array(9).fill(null), turn: null, symbols: {}, winner: null, notice: 'На ход даётся 30 секунд. Превышение — поражение.' }, deadlineAt: null, _timer: null }; gameRooms.set(id, room); userActiveRoom.set(String(tgid), id); return room; }
  function rpsOutcome(a,b){ if (a===b) return 0; if ((a==='rock'&&b==='scissors')||(a==='scissors'&&b==='paper')||(a==='paper'&&b==='rock')) return 1; return -1; }
  function tttCheckWinner(board){ const lines = [ [0,1,2],[3,4,5],[6,7,8], [0,3,6],[1,4,7],[2,5,8], [0,4,8],[2,4,6] ]; for (const [a,b,c] of lines){ if (board[a] && board[a]===board[b] && board[a]===board[c]) return board[a]; } if (board.every(v=>v)) return 'draw'; return null; }

  app.get('/api/games/rooms', (req, res)=>{ const game = (req.query.game === 'ttt') ? 'ttt' : 'rps'; const bet = parseInt(req.query.bet || '0', 10) || 0; const list = []; for (const room of gameRooms.values()){ if (room.status==='waiting' && room.game===game && (!bet || Number(room.bet)===bet)) { list.push(serializeRoom(room)); } } res.json({ ok:true, rooms:list.slice(0,50) }); });
  app.post('/api/games/rooms', async (req, res)=>{ try{ const { tgid: bodyTgid, game, bet } = req.body || {}; const authTgid = getAuthTgid(req); const playerTgid = authTgid || bodyTgid; const G = (game === 'ttt') ? 'ttt' : 'rps'; const B = Math.max(1, parseInt(bet,10)||0); if (authTgid && bodyTgid && String(authTgid)!==String(bodyTgid)) return res.json({ ok:false, message:'Auth mismatch' }); if (!playerTgid || !B) return res.status(400).json({ ok:false, message:'Invalid params' }); if (userActiveRoom.get(String(playerTgid))) return res.json({ ok:false, message:'У вас уже есть активная комната' }); const reserve = await db.tryReserveScube(playerTgid, B); if (!reserve.ok) return res.json(reserve); const room = createRoom(playerTgid, G, B); if (G==='ttt') { room.state.turn = Math.random()<0.5 ? String(room.creator) : null; } res.json({ ok:true, room: serializeRoom(room) }); } catch (err){ res.status(500).json({ ok:false, message:'Server error' }); } });
  app.post('/api/games/rooms/:id/join', async (req, res)=>{ try{ const id = req.params.id; const authTgid = getAuthTgid(req); const bodyTgid = (req.body && req.body.tgid) || null; if (authTgid && bodyTgid && String(authTgid)!==String(bodyTgid)) return res.json({ ok:false, message:'Auth mismatch' }); const tgid = authTgid || bodyTgid; const room = gameRooms.get(id); if (!room) return res.status(404).json({ ok:false, message:'Room not found' }); if (room.status!=='waiting') return res.json({ ok:false, message:'Комната уже занята' }); if (String(room.creator) === String(tgid)) return res.json({ ok:false, message:'Нельзя присоединиться к своей комнате' }); if (userActiveRoom.get(String(tgid))) return res.json({ ok:false, message:'У вас уже есть активная комната' }); const reserve = await db.tryReserveScube(tgid, room.bet); if (!reserve.ok) return res.json(reserve); room.opponent = tgid; room.status = 'active'; if (room.game==='ttt'){ room.state.symbols = { [String(room.creator)] : 'X', [String(tgid)] : 'O' }; if (!room.state.turn) room.state.turn = String(room.creator); startTttTimer(room); } else if (room.game==='rps'){ startRpsTimer(room); } userActiveRoom.set(String(tgid), id); res.json({ ok:true, room: serializeRoom(room) }); } catch(err){ res.status(500).json({ ok:false, message:'Server error' }); } });
  app.get('/api/games/rooms/:id', (req,res)=>{ const room = gameRooms.get(req.params.id); if (!room) return res.status(404).json({ ok:false, message:'Room not found' }); res.json({ ok:true, room: serializeRoom(room) }); });
  app.post('/api/games/rooms/:id/move', async (req,res)=>{ try{ const room = gameRooms.get(req.params.id); if (!room) return res.status(404).json({ ok:false, message:'Room not found' }); const authTgid = getAuthTgid(req); const bodyTgid = (req.body && req.body.tgid) || null; if (authTgid && bodyTgid && String(authTgid)!==String(bodyTgid)) return res.json({ ok:false, message:'Auth mismatch' }); const tgid = authTgid || bodyTgid; if (!tgid) return res.status(400).json({ ok:false, message:'Invalid player' }); if (room.status!=='active' && room.status!=='waiting') return res.json({ ok:false, message:'Игра завершена' }); if (room.game==='rps'){ const move = String(req.body.move||'').toLowerCase(); if (!['rock','paper','scissors'].includes(move)) return res.status(400).json({ ok:false, message:'Invalid move' }); if (room.state.moves[String(tgid)]) return res.json({ ok:false, message:'Ход уже сделан' }); room.state.moves[String(tgid)] = move; if (room.opponent && room.state.moves[String(room.creator)] && room.state.moves[String(room.opponent)]){ const a = room.state.moves[String(room.creator)]; const b = room.state.moves[String(room.opponent)]; const out = rpsOutcome(a,b); clearRoomTimer(room); if (out===0){ await finishRoomWithWinner(room, null, 'both_moved'); room.state.result = Object.assign({}, room.state.result || {}, { a, b }); } else if (out===1){ await finishRoomWithWinner(room, room.creator, 'both_moved'); room.state.result = Object.assign({}, room.state.result || {}, { a, b }); } else { await finishRoomWithWinner(room, room.opponent, 'both_moved'); room.state.result = Object.assign({}, room.state.result || {}, { a, b }); } } return res.json({ ok:true, room: serializeRoom(room) }); } else if (room.game==='ttt'){ const idx = parseInt(req.body.idx,10); if (!(idx>=0 && idx<9)) return res.status(400).json({ ok:false, message:'Invalid cell' }); const sym = room.state.symbols[String(tgid)]; if (!sym) return res.status(403).json({ ok:false, message:'Not a player' }); if (room.state.turn !== String(tgid)) return res.json({ ok:false, message:'Ход соперника' }); if (room.state.board[idx]) return res.json({ ok:false, message:'Клетка занята' }); room.state.board[idx] = sym; const w = tttCheckWinner(room.state.board); clearRoomTimer(room); if (w==='draw'){ await finishRoomWithWinner(room, null, 'board_draw'); } else if (w){ const winnerTgid = Object.entries(room.state.symbols).find(([,s])=>s===w)[0]; await finishRoomWithWinner(room, Number(winnerTgid), 'board_win'); } else { const next = (String(tgid)===String(room.creator)) ? String(room.opponent) : String(room.creator); room.state.turn = next; startTttTimer(room); } return res.json({ ok:true, room: serializeRoom(room) }); } return res.status(400).json({ ok:false, message:'Unknown game' }); } catch(err){ res.status(500).json({ ok:false, message:'Server error' }); } });
  app.post('/api/games/rooms/:id/leave', async (req,res)=>{ try{ const room = gameRooms.get(req.params.id); const authTgid = getAuthTgid(req); const bodyTgid = (req.body && req.body.tgid) || null; if (authTgid && bodyTgid && String(authTgid)!==String(bodyTgid)) return res.json({ ok:false, message:'Auth mismatch' }); const tgid = authTgid || bodyTgid; if (!room) return res.status(404).json({ ok:false, message:'Room not found' }); const isCreator = String(room.creator)===String(tgid); const isOpponent = String(room.opponent||'')===String(tgid); if (!isCreator && !isOpponent) return res.status(403).json({ ok:false, message:'Not a participant' }); if (room.status==='waiting'){ clearRoomTimer(room); await db.creditScube(room.creator, room.bet); room.status='finished'; } else if (room.status==='active'){ const winner = isCreator ? room.opponent : room.creator; clearRoomTimer(room); await db.creditScube(winner, room.bet*2); room.status='finished'; room.state.forfeit = String(tgid); } userActiveRoom.delete(String(room.creator)); if (room.opponent) userActiveRoom.delete(String(room.opponent)); res.json({ ok:true, room: serializeRoom(room) }); } catch(err){ res.status(500).json({ ok:false, message:'Server error' }); } });
}

module.exports = { attachGameRoutes };
