import { apiBase } from './state.js';

export function initGames(getTgid, onAfterState){
  let selectedGame = 'rps'; let selectedBet = 50; let currentRoomId = null; let roomPollIv = null; let roomCountdownIv = null;
  const roomsList = document.getElementById('rooms-list');
  const gameCards = document.getElementById('game-cards');
  const betSelector = document.getElementById('bet-selector');
  const createRoomBtn = document.getElementById('create-room');
  const gameStage = document.getElementById('game-stage');

  function setInMatch(on){ const root = document.querySelector('.game-root'); if (!root) return; if (on) root.classList.add('in-match'); else root.classList.remove('in-match'); }
  function renderRooms(rooms){ if (!roomsList) return; roomsList.innerHTML=''; if (!rooms || !rooms.length){ const empty = document.createElement('div'); empty.className='store-empty'; empty.textContent='Нет доступных комнат. Создайте свою!'; roomsList.appendChild(empty); return; } rooms.forEach(r=>{ const card=document.createElement('div'); card.className='room-card'; const meta=document.createElement('div'); meta.className='room-meta'; const title=document.createElement('div'); title.className='room-title'; title.textContent = `${r.game === 'rps' ? 'КНБ' : 'Крестики-нолики'} • Ставка ${r.bet}`; const sub=document.createElement('div'); sub.className='room-sub'; sub.textContent = `Создатель: ${r.creator}`; meta.append(title, sub); const join=document.createElement('button'); join.className='join-btn'; join.textContent='Вступить'; join.addEventListener('click', ()=> joinRoom(r.id)); card.append(meta, join); roomsList.appendChild(card); }); }
  async function loadRooms(){ try{ const res = await fetch(`${apiBase}/games/rooms?game=${selectedGame}&bet=${selectedBet}`); const json = await res.json(); if (json.ok) renderRooms(json.rooms); } catch(e){ console.warn('rooms load failed', e); } }
  async function createRoom(){ const tgid = getTgid(); if (!tgid) return alert('tgid is required'); try{ const res = await fetch(`${apiBase}/games/rooms`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ tgid, game: selectedGame, bet: selectedBet }) }); const json = await res.json(); if (!json.ok) return alert(json.message || 'Не удалось создать комнату'); currentRoomId = json.room.id; openRoom(json.room); if (onAfterState) onAfterState(); } catch(e){ console.warn('create room failed', e); } }
  async function joinRoom(id){ const tgid = getTgid(); if (!tgid) return alert('tgid is required'); try{ const res = await fetch(`${apiBase}/games/rooms/${id}/join`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ tgid }) }); const json = await res.json(); if (!json.ok) return alert(json.message || 'Не удалось войти в комнату'); currentRoomId = json.room.id; openRoom(json.room); if (onAfterState) onAfterState(); } catch(e){ console.warn('join room failed', e); } }
  async function leaveRoom(){ if (!currentRoomId) return; try{ const tgid = getTgid(); await fetch(`${apiBase}/games/rooms/${currentRoomId}/leave`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ tgid }) }); } catch(e){}
    clearInterval(roomPollIv); roomPollIv=null; if (roomCountdownIv) { clearInterval(roomCountdownIv); roomCountdownIv=null; } currentRoomId=null; setInMatch(false); gameStage.innerHTML=''; gameStage.classList.add('hidden'); await loadRooms(); if (onAfterState) onAfterState(); }
  function startRoomPolling(){ if (roomPollIv) clearInterval(roomPollIv); roomPollIv = setInterval(async ()=>{ if (!currentRoomId) return; try{ const res = await fetch(`${apiBase}/games/rooms/${currentRoomId}`); const json = await res.json(); if (json.ok) openRoom(json.room); } catch(e){} }, 1500); }
  function openRoom(room){ if (!gameStage) return; const active = room.status !== 'finished'; setInMatch(active); if (!active && currentRoomId) { leaveRoom(); return; } const gamesTabBtn = Array.from(document.querySelectorAll('.tab-button')).find(b=>b.dataset.tab==='games'); if (gamesTabBtn) gamesTabBtn.click(); gameStage.classList.remove('hidden'); if (roomCountdownIv) { clearInterval(roomCountdownIv); roomCountdownIv=null; } if (room.game==='rps') renderRps(room); else renderTtt(room); if (active && !roomPollIv) startRoomPolling(); if (!active && roomPollIv) { clearInterval(roomPollIv); roomPollIv=null; } }
  function renderRps(room){ const tgid = String(getTgid()); const opp = tgid === String(room.creator) ? String(room.opponent||'') : String(room.creator); const moves = room.state && room.state.moves || {}; const myMove = moves[tgid]; const oppMove = moves[opp]; const finished = room.status === 'finished'; const wrap=document.createElement('div'); const title=document.createElement('div'); title.className='room-title'; title.textContent=`КНБ • Ставка ${room.bet}`; const notice=document.createElement('div'); notice.className='room-sub'; notice.textContent='Сделайте ход за 30 секунд, иначе поражение.'; const timer=document.createElement('div'); timer.className='turn-timer-badge'; if (room.deadlineAt && room.status==='active'){ const update=()=>{ const remain = Math.max(0, Math.ceil((room.deadlineAt - Date.now())/1000)); timer.textContent = `⏳ Осталось: ${remain}с`; }; update(); roomCountdownIv = setInterval(update, 500); }
    const controls=document.createElement('div'); controls.className='rps-controls'; ['rock','paper','scissors'].forEach(m=>{ const btn=document.createElement('button'); btn.className='rps-btn'; btn.textContent = m==='rock'?'✊':(m==='paper'?'✋':'✌️'); btn.disabled = !!myMove || finished || !room.opponent; btn.addEventListener('click', ()=> submitMove(room.id, { move: m })); controls.appendChild(btn); });
    const result=document.createElement('div'); result.className='rps-result'; if (!room.opponent) result.textContent='Ожидание соперника...'; else if (!myMove) result.textContent='Сделайте ход'; else if (!oppMove) result.textContent='Ожидаем ход соперника'; if (finished){ if (room.state && room.state.result){ const r = room.state.result; const banner=document.createElement('div'); if (r.type==='draw') { banner.className='result-banner draw'; banner.textContent='Ничья. Ставки возвращены'; } else if (String(r.winner)===tgid) { banner.className='result-banner win'; banner.textContent='Победа!'; } else { banner.className='result-banner lose'; banner.textContent='Поражение'; } wrap.appendChild(banner); } }
    const isCreatorWaiting = !finished && !room.opponent && String(room.creator)===tgid; const leave=document.createElement('button'); leave.className='join-btn'; leave.textContent = finished ? 'Выйти' : (isCreatorWaiting ? 'Отменить' : 'Сдаться'); leave.addEventListener('click', leaveRoom);
    wrap.append(title, notice, timer, controls, result, leave); gameStage.innerHTML=''; gameStage.appendChild(wrap);
  }
  function renderTtt(room){ const tgid = String(getTgid()); const board = room.state && room.state.board || Array(9).fill(null); const turn = room.state && room.state.turn; const symbols = room.state && room.state.symbols || {}; const mySym = symbols[tgid]; const finished = room.status === 'finished'; const wrap=document.createElement('div'); const title=document.createElement('div'); title.className='room-title'; title.textContent = `Крестики-нолики • Ставка ${room.bet}`; const notice=document.createElement('div'); notice.className='room-sub'; notice.textContent='На ход даётся 30 секунд. Превышение - поражение.'; const timer=document.createElement('div'); timer.className='turn-timer-badge'; if (room.deadlineAt && room.status==='active'){ const update=()=>{ const remain = Math.max(0, Math.ceil((room.deadlineAt - Date.now())/1000)); const who = String(turn)===tgid ? 'Ваш ход' : 'Ход соперника'; timer.textContent = `⏳ ${who}: ${remain}с`; }; update(); roomCountdownIv = setInterval(update, 500); }
    const grid=document.createElement('div'); grid.className='ttt-board'; board.forEach((cell, idx)=>{ const c=document.createElement('div'); c.className='ttt-cell'; c.textContent = cell || ''; const canClick = !finished && mySym && String(turn)===tgid && !cell; if (canClick) c.addEventListener('click', ()=> submitMove(room.id, { idx })); grid.appendChild(c); }); const status=document.createElement('div'); status.className='ttt-status'; if (!room.opponent) status.textContent='Ожидание соперника...'; else if (finished){ let banner; if (room.state && room.state.winner){ const win = String(room.state.winner)===tgid; banner=document.createElement('div'); banner.className = 'result-banner ' + (win ? 'win' : 'lose'); banner.textContent = win ? 'Победа!' : 'Поражение'; } else { banner=document.createElement('div'); banner.className='result-banner draw'; banner.textContent='Ничья'; } wrap.appendChild(banner); } else if (String(turn)===tgid) status.textContent='Ваш ход'; else status.textContent='Ход соперника'; const isCreatorWaiting = !finished && !room.opponent && String(room.creator)===tgid; const leave=document.createElement('button'); leave.className='join-btn'; leave.textContent = finished ? 'Выйти' : (isCreatorWaiting ? 'Отменить' : 'Сдаться'); leave.addEventListener('click', leaveRoom); wrap.append(title, notice, timer, grid, status, leave); gameStage.innerHTML=''; gameStage.appendChild(wrap); }
  async function submitMove(roomId, payload){ try{ const tgid = getTgid(); const res = await fetch(`${apiBase}/games/rooms/${roomId}/move`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ tgid, ...payload }) }); const json = await res.json(); if (!json.ok) return; openRoom(json.room); if (json.room.status==='finished') { if (roomCountdownIv) { clearInterval(roomCountdownIv); roomCountdownIv=null; } clearInterval(roomPollIv); roomPollIv=null; if (onAfterState) onAfterState(); } } catch(e){} }

  if (gameCards){ gameCards.addEventListener('click', (e)=>{ const btn = e.target.closest('.game-card'); if (!btn) return; selectedGame = btn.dataset.game || 'rps'; loadRooms(); }); }
  if (betSelector){ betSelector.addEventListener('click', (e)=>{ const chip = e.target.closest('.bet-chip'); if (!chip) return; const v = parseInt(chip.dataset.bet,10); if (!v) return; selectedBet = v; betSelector.querySelectorAll('.bet-chip').forEach(c=>c.classList.remove('active')); chip.classList.add('active'); loadRooms(); }); const def = betSelector.querySelector('[data-bet="50"]'); if (def) def.classList.add('active'); }
  if (createRoomBtn){ createRoomBtn.addEventListener('click', createRoom); }
  const gamesTabBtn = Array.from(document.querySelectorAll('.tab-button')).find(b=>b.dataset.tab==='games'); if (gamesTabBtn){ gamesTabBtn.addEventListener('click', ()=>{ if (!currentRoomId) loadRooms(); }); }

  return { loadRooms, createRoom, joinRoom, leaveRoom };
}
